version: '3.5'
services:
  milvus-standalone:
    image: milvusdb/milvus:v2.4.0
    container_name: milvus-standalone
    environment:
      - TZ=UTC
    ports:
      - "19530:19530"   # Milvus gRPC
      - "9091:9091"     # Milvus RESTful API (if enabled)
    command: ["milvus", "run", "standalone"]